spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Efarming
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop          # auto update schema
    show-sql: true              # show SQL queries in console
    properties:
      hibernate:
        format_sql: true        # âœ… format SQL nicely
        use_sql_comments: true  # show helpful comments in SQL
        dialect: org.hibernate.dialect.MySQL8Dialect

#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql

server:
  port: 8080
